

name: Phoenix Test Automation Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  schedule:
    - cron: "00 20 * * *"
    - cron: "00 21 * * *"

  workflow_dispatch:
    inputs: 
     env:
      description: "Environment"
      type: choice
      options: [qa,uat,dev]
      default: qa
      required: false

     suiteXmlFile:
      description: "Testng Xml File"
      type: choice
      options: [testng.xml,smoke.xml,regression.xml]
      default: testng.xml
      required: true
  

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Default Values for Exceution
      id: default
      run: | 
            echo "suiteXmlFile=${{github.event.inputs.suiteXmlFile || 'testng.xml'}}" >> $GITHUB_OUTPUT  
        
    - name: Execute test automation framework
      run: mvn clean test -DsuiteXmlFile="${{steps.default.outputs.suiteXmlFile}}"
    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v7.0.1
      with:
         name: SureFire Reports
         path : target/surefire-reports/
         retention-days: 10
        

   
